#
##DATABASE
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/thedaybookdb
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#  #spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/paymentdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

#management:
#  tracing:
#    enabled: true
#
#micrometer:
#  tracing:
#    sampling:
#      probability: 1.0  # sample all traces; adjust as needed
#    zipkin:
#      enabled: true
#      endpoint: http://localhost:9411/api/v2/spans  # Zipkin's ingestion endpoint

# Define here the Eureka Server you want ths service to point to.

# ===> Commented this because I am using config server to manage all my repeated configurations.

#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}