server:
  port: 9090
spring:
  application:
    name: Api-Gateway
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: ORDER-SERVICE
          predicates:
            - Path=/orders, /orders/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**