server:
  port: 9090
spring:
  application:
    name: Api-Gateway
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders, /orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name : ORDER-SERVICE
                    fallbackuri: forward:/orderServiceFallBack
            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: PAYMENT-SERVICE
                    fallbackuri: forward:/paymentServiceFallBack
            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: PRODUCT-SERVICE
                    fallbackuri: forward:/productServiceFallBack