
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/order_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: Order-Service
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

# Define here the Eureka Server you want ths service to point to.
#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
